/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/upbound/upjet/pkg/resource"
	"github.com/upbound/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this Git
func (mg *Git) GetTerraformResourceType() string {
	return "flux_bootstrap_git"
}

// GetConnectionDetailsMapping for this Git
func (tr *Git) GetConnectionDetailsMapping() map[string]string {
	return map[string]string{"gpg_passphrase": "spec.forProvider.gpgPassphraseSecretRef", "http[*].password": "spec.forProvider.http[*].passwordSecretRef", "ssh[*].password": "spec.forProvider.ssh[*].passwordSecretRef", "ssh[*].private_key": "spec.forProvider.ssh[*].privateKeySecretRef"}
}

// GetObservation of this Git
func (tr *Git) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this Git
func (tr *Git) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this Git
func (tr *Git) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this Git
func (tr *Git) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this Git
func (tr *Git) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this Git using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *Git) LateInitialize(attrs []byte) (bool, error) {
	params := &GitParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *Git) GetTerraformSchemaVersion() int {
	return 0
}
